pipeline {

    agent any

    environment {
      PASS = credentials('docker-hub-registry-pass')
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                    ./jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./jenkins/build/build.sh
                   '''
            }

            post {
              success {
                archiveArtifacts artifacts: 'Initialize-Spring-Boot-Security-Jwt/target/*.jar', fingerprint: true
              }
           }

        }

        stage('Test') {
            steps {
                sh './jenkins/test/mvn.sh mvn test'
            }

            post {
              always {
                junit 'Initialize-Spring-Boot-Security-Jwt/target/surefire-reports/*.xml'
              }
           }
        }

        stage('Push') {
            steps {
                sh './jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh './jenkins/deploy/deploy.sh'
            }
        }
    }
}

