#!/bin/bash

# Get branch name from ref head

if ! [ -t 0 ]; then
  read -a ref
fi
IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"
echo "$branch"

if [ $branch == "master" ]; then
crumb=$(curl -u "jenkins:12345" -s 'http://jenkins:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
curl -u "jenkins:12345" -H "$crumb" -X POST http://jenkins:8080/job/gitlab-maven-job/build?delay=0sec

  if [ $? -eq 0 ];then
    echo "*** Ok"
  else
    echo "*** Error"

  fi
fi
